import React from 'react';

export default function Instrunctions() {
  return (
    <div>
      <h1>A</h1>
      <ol>
        b
        <li>
          <p>c</p>
          <p>
          </p>
        </li>
        <li>
          <p>
            d</p>
          <p>e</p>
        </li>
        <li>
          <p>f          </p>
          <p>g</p>
        </li>
        <li>
          <p>
            h:
          </p>
          <p>i</p>
        </li>
        <li>
          <p>
            j:
          </p>
          <p>k</p>
        </li>
        <li>
          <h3>l</h3>
          <p>m</p>
          <p>n</p>
          <ul>
            <li>o</li>
            <li>p</li>
            <li>q</li>
            <li>r</li>
          </ul>
          <p>s:
          </p>
          <ul>
            <li>t</li>
            <li>u</li>
            <li>v</li>
            <li>w</li>
          </ul>
        </li>
      </ol>
      <h1>x</h1>
      <ol>
        <li>
          <p>y:</p>
          <p>z</p>
        </li>
        <li>
          <p>A:</p> <p>b</p>
        </li>
        <li>
          <p>c: </p>
          <p>d</p>
        </li>
        <li>
          <p>
            e
          </p>
        </li>
        <li>f</li>
        <h3>
          g
        </h3>
        <h1>h</h1>
        <h1>i</h1>
      </ol>
    </div>
  );
}
